// GENERATED by scripts/sync_upstreams.py; DO NOT EDIT.
// upstream: Impeccable
// source: https://github.com/pbakaus/impeccable/blob/eda81f09378d32c93fec6d3cd8f1ecbf13595e15/.agents/skills/impeccable/scripts/detector/shared/fonts.mjs
// commit: eda81f09378d32c93fec6d3cd8f1ecbf13595e15
// source_sha256: 869c297295a10082d87988f31c136c5df9ddad84da0c2bbba2e85e1261e320a6
// transform: copy
// SPDX-License-Identifier: Apache-2.0

const GOOGLE_FONTS_URL_RE = /fonts\.googleapis\.com\/css2?\?[^"'\s)<>]*/gi;

function normalizeGoogleFontFamilyParam(value) {
  return String(value || '')
    .split('|')
    .map(part => part.split(':')[0].trim().toLowerCase())
    .filter(Boolean);
}

function extractGoogleFontFamilies(text) {
  const families = [];
  if (!text) return families;

  GOOGLE_FONTS_URL_RE.lastIndex = 0;
  let urlMatch;
  while ((urlMatch = GOOGLE_FONTS_URL_RE.exec(text)) !== null) {
    const url = urlMatch[0];
    const queryStart = url.indexOf('?');
    if (queryStart === -1) continue;

    const params = new URLSearchParams(url.slice(queryStart + 1).replace(/&amp;/g, '&'));
    for (const value of params.getAll('family')) {
      families.push(...normalizeGoogleFontFamilyParam(value));
    }
  }

  return families;
}

export { extractGoogleFontFamilies };
