// GENERATED by scripts/sync_upstreams.py; DO NOT EDIT.
// upstream: Impeccable
// source: https://github.com/pbakaus/impeccable/blob/eda81f09378d32c93fec6d3cd8f1ecbf13595e15/.agents/skills/impeccable/scripts/detector/shared/page.mjs
// commit: eda81f09378d32c93fec6d3cd8f1ecbf13595e15
// source_sha256: b4cef5548d84fa90d15e6b42b20be9ef74ed05e4e6e46076ec5acc61b343315c
// transform: copy
// SPDX-License-Identifier: Apache-2.0

/** Check if content looks like a full page (not a component/partial) */
function isFullPage(content) {
  const stripped = content.replace(/<!--[\s\S]*?-->/g, '');
  return /<!doctype\s|<html[\s>]|<head[\s>]/i.test(stripped);
}

export { isFullPage };
