#!/usr/bin/env python3
"""确定性同步 Taste 与 Impeccable 的审核白名单。

此脚本只管理带 GENERATED 标记的引用与检测器文件。它不会读取或改写
SKILL.md、agents、README、文档或任何编排规则。
"""

from __future__ import annotations

import argparse
import datetime as dt
import fnmatch
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "upstreams.lock.json"
SKILL_ROOT = ROOT / "plugins" / "taste-impeccable" / "skills" / "design-frontend"
REFERENCES_ROOT = SKILL_ROOT / "references"
SCRIPTS_ROOT = SKILL_ROOT / "scripts"
GENERATED_MARKER = "GENERATED by scripts/sync_upstreams.py"
HEX_COMMIT = re.compile(r"^[0-9a-f]{40}$")
NOTICE_PIN_START = "<!-- BEGIN GENERATED UPSTREAM PINS -->"
NOTICE_PIN_END = "<!-- END GENERATED UPSTREAM PINS -->"
ATTRIBUTION_TARGETS = {
    ("taste", "license_path"): ROOT / "LICENSES" / "TASTE-MIT.txt",
    ("impeccable", "license_path"): ROOT
    / "LICENSES"
    / "IMPECCABLE-APACHE-2.0.txt",
    ("impeccable", "notice_path"): ROOT / "LICENSES" / "IMPECCABLE-NOTICE.md",
}


class SyncError(RuntimeError):
    """可行动的同步错误。"""


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def run_git(args: list[str], *, cwd: Path | None = None) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        command = "git " + " ".join(args)
        detail = result.stderr.strip() or result.stdout.strip()
        raise SyncError(f"{command} 失败：{detail}")
    return result.stdout


def load_lock() -> dict[str, Any]:
    try:
        lock = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SyncError(f"无法读取 {LOCK_PATH}: {exc}") from exc
    if lock.get("schema_version") != 1:
        raise SyncError("不支持的 upstreams.lock.json schema_version")
    if lock.get("policy", {}).get("orchestration_is_manual") is not True:
        raise SyncError("锁文件必须明确 orchestration_is_manual=true")
    return lock


def save_lock(lock: dict[str, Any]) -> None:
    LOCK_PATH.write_text(
        json.dumps(lock, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def resolve_ref(repository: str, ref: str) -> str:
    """解析 ref；对 annotated tag 必须使用 peeled commit，而不是 tag object。"""
    query = [ref]
    if ref.startswith("refs/tags/"):
        query.append(f"{ref}^{{}}")
    output = run_git(["ls-remote", repository, *query])
    entries: dict[str, str] = {}
    for line in output.splitlines():
        commit, name = line.split(maxsplit=1)
        entries[name] = commit
    peeled = entries.get(f"{ref}^{{}}")
    commit = peeled or entries.get(ref)
    if not commit or not HEX_COMMIT.fullmatch(commit):
        raise SyncError(f"无法解析 {repository} 的 {ref}")
    return commit


def semantic_tag_key(tag: str) -> tuple[int, ...] | None:
    match = re.fullmatch(r"skill-v(\d+(?:\.\d+)*)", tag)
    if not match:
        return None
    return tuple(int(piece) for piece in match.group(1).split("."))


def resolve_latest_release(repository: str, pattern: str) -> tuple[str, str]:
    output = run_git(["ls-remote", "--tags", repository, pattern, f"{pattern}^{{}}"])
    raw: dict[str, str] = {}
    peeled: dict[str, str] = {}
    for line in output.splitlines():
        commit, full_ref = line.split(maxsplit=1)
        short = full_ref.removeprefix("refs/tags/")
        if short.endswith("^{}"):
            peeled[short[:-3]] = commit
        else:
            raw[short] = commit
    candidates = [
        (semantic_tag_key(tag), tag)
        for tag in raw
        if fnmatch.fnmatch(tag, pattern) and semantic_tag_key(tag) is not None
    ]
    if not candidates:
        raise SyncError(f"未找到匹配 {pattern} 的稳定 Skill tag")
    _, tag = max(candidates)
    return tag, peeled.get(tag, raw[tag])


class GitSnapshot:
    def __init__(self, repository: str, commit: str) -> None:
        if not HEX_COMMIT.fullmatch(commit):
            raise SyncError(f"非法 commit: {commit}")
        self.repository = repository
        self.commit = commit
        self._temp = tempfile.TemporaryDirectory(prefix="taste-impeccable-sync-")
        self.path = Path(self._temp.name)
        run_git(["init", "--quiet"], cwd=self.path)
        run_git(["remote", "add", "origin", repository], cwd=self.path)
        run_git(["fetch", "--quiet", "--depth=1", "origin", commit], cwd=self.path)
        fetched = run_git(["rev-parse", "FETCH_HEAD^{commit}"], cwd=self.path).strip()
        if fetched != commit:
            raise SyncError(f"获取到的 commit 不匹配：期望 {commit}，实际 {fetched}")

    def read(self, source_path: str) -> bytes:
        result = subprocess.run(
            ["git", "show", f"{self.commit}:{source_path}"],
            cwd=self.path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if result.returncode != 0:
            detail = result.stderr.decode("utf-8", errors="replace").strip()
            raise SyncError(f"{source_path} 在 {self.commit} 不存在：{detail}")
        return result.stdout

    def close(self) -> None:
        self._temp.cleanup()


def markdown_header(
    *,
    upstream: str,
    web_repository: str,
    commit: str,
    source_path: str,
    source_digest: str,
    transform: str,
    license_id: str,
) -> str:
    source_url = f"{web_repository}/blob/{commit}/{source_path}"
    return (
        "<!--\n"
        f"{GENERATED_MARKER}; DO NOT EDIT.\n"
        f"upstream: {upstream}\n"
        f"source: {source_url}\n"
        f"commit: {commit}\n"
        f"source_sha256: {source_digest}\n"
        f"transform: {transform}\n"
        f"SPDX-License-Identifier: {license_id}\n"
        "-->\n\n"
    )


def script_header(
    *,
    upstream: str,
    web_repository: str,
    commit: str,
    source_path: str,
    source_digest: str,
    transform: str,
    license_id: str,
) -> str:
    source_url = f"{web_repository}/blob/{commit}/{source_path}"
    return (
        f"// {GENERATED_MARKER}; DO NOT EDIT.\n"
        f"// upstream: {upstream}\n"
        f"// source: {source_url}\n"
        f"// commit: {commit}\n"
        f"// source_sha256: {source_digest}\n"
        f"// transform: {transform}\n"
        f"// SPDX-License-Identifier: {license_id}\n\n"
    )


def between(text: str, start: str, end: str | None = None) -> str:
    try:
        start_index = text.index(start)
    except ValueError as exc:
        raise SyncError(f"上游结构变化，找不到起始标记：{start}") from exc
    if end is None:
        return text[start_index:].rstrip() + "\n"
    try:
        end_index = text.index(end, start_index + len(start))
    except ValueError as exc:
        raise SyncError(f"上游结构变化，找不到结束标记：{end}") from exc
    return text[start_index:end_index].rstrip() + "\n"


def remove_between(text: str, start: str, end: str) -> str:
    try:
        start_index = text.index(start)
        end_index = text.index(end, start_index + len(start))
    except ValueError as exc:
        raise SyncError(f"上游结构变化，无法过滤区间：{start} -> {end}") from exc
    return text[:start_index] + text[end_index:]


def generate_taste(
    config: dict[str, Any],
    snapshot: GitSnapshot,
    source_hashes: dict[str, str],
) -> dict[Path, bytes]:
    source_path = config["skill_source"]
    raw = snapshot.read(source_path)
    digest = sha256(raw)
    source_hashes[f"taste:{source_path}"] = digest
    text = raw.decode("utf-8")
    # 去掉上游 Skill frontmatter，避免生成的引用被识别成额外 Skill。
    if not text.startswith("---\n"):
        raise SyncError("Taste SKILL.md frontmatter 结构变化")
    _, _, body = text.partition("---\n")
    _, separator, body = body.partition("---\n")
    if not separator:
        raise SyncError("Taste SKILL.md frontmatter 未闭合")
    body = body.lstrip()

    pieces = {
        "taste/direction.md": between(body, "# tasteskill:", "## 3. DEFAULT ARCHITECTURE"),
        "taste/foundation.md": between(
            body, "## 3. DEFAULT ARCHITECTURE", "## 5. CONTEXT-AWARE PROACTIVITY"
        ),
        "taste/motion.md": between(
            body, "## 5. CONTEXT-AWARE PROACTIVITY", "## 6. PERFORMANCE & ACCESSIBILITY"
        ),
        "taste/quality.md": (
            "# Taste Quality Guardrails\n\n"
            + between(body, "## 6. PERFORMANCE & ACCESSIBILITY", "## 7. DIAL DEFINITIONS")
            + "\n"
            + between(body, "## 8. DARK MODE PROTOCOL", "## 11. REDESIGN PROTOCOL")
        ),
        "taste/redesign.md": between(
            body, "## 11. REDESIGN PROTOCOL", "## 12. THE BLOCK LIBRARY"
        ),
        "taste/preflight.md": (
            "# Taste Scope and Pre-flight\n\n"
            + between(body, "## 13. OUT OF SCOPE", "# APPENDICES")
        ),
        "taste/design-systems.md": between(body, "# APPENDICES"),
    }

    declared = set(config["included_sections"])
    if set(pieces) != declared:
        raise SyncError(
            f"Taste 输出白名单不一致：lock={sorted(declared)} generator={sorted(pieces)}"
        )

    generated: dict[Path, bytes] = {}
    for relative, content in pieces.items():
        sections = ",".join(config["included_sections"][relative])
        header = markdown_header(
            upstream="Taste",
            web_repository=config["web_repository"],
            commit=config["commit"],
            source_path=source_path,
            source_digest=digest,
            transform=f"extract-sections:{sections}",
            license_id=config["license"],
        )
        generated[REFERENCES_ROOT / relative] = (
            header + normalize_markdown(content)
        ).encode()
    return generated


def filter_impeccable_lines(text: str) -> str:
    """移除指向被过滤修复命令的行，避免审校参考偷偷恢复写入能力。"""
    lines = [line for line in text.splitlines() if "$impeccable" not in line]
    return "\n".join(lines).rstrip() + "\n"


def normalize_markdown(text: str) -> str:
    """稳定生成物格式，避免上游行尾空白污染 diff 与提交门禁。"""
    return "\n".join(line.rstrip() for line in text.splitlines()).rstrip() + "\n"


def generate_impeccable_references(
    config: dict[str, Any],
    snapshot: GitSnapshot,
    source_hashes: dict[str, str],
) -> dict[Path, bytes]:
    critique_path = config["included_references"]["impeccable/review-method.md"]
    audit_path = config["included_references"]["impeccable/technical-audit.md"]
    critique_raw = snapshot.read(critique_path)
    audit_raw = snapshot.read(audit_path)
    critique_digest = sha256(critique_raw)
    audit_digest = sha256(audit_raw)
    source_hashes[f"impeccable:{critique_path}"] = critique_digest
    source_hashes[f"impeccable:{audit_path}"] = audit_digest
    critique = critique_raw.decode("utf-8")
    audit = audit_raw.decode("utf-8")

    invariants = between(critique, "### Hard Invariants", "### Setup")
    invariants = "\n".join(
        line
        for line in invariants.splitlines()
        if "local server started only for critique" not in line
        and "user-visible overlay" not in line
    ).rstrip()
    orchestration = between(
        critique, "### Assessment Orchestration", "Codex sub-agent gate"
    ).rstrip()
    assessment_a = between(
        critique, "### Assessment A: Design Review", "### Assessment B:"
    ).rstrip()
    assessment_b = between(
        critique, "### Assessment B: Detector + Browser Evidence", "Browser visualization is required"
    ).rstrip()
    report = between(
        critique, "### Generate Combined Critique Report", "### Persist the Snapshot"
    )
    report = between(report, "### Generate Combined Critique Report", "#### Questions to Consider")
    report = report.replace(
        "The persisted snapshot is only an archive/backlog for later commands.", ""
    )
    report = report.replace(
        "The persisted snapshot must record the applicable maximum and which heuristics were scored n/a.",
        "The report must record the applicable maximum and which heuristics were scored n/a.",
    )
    report = re.sub(
        r"\n\*\*Visual overlays\*\* \(if injection succeeded\):.*?\n",
        "\n",
        report,
        flags=re.DOTALL,
    )
    report = report.replace(
        "If `AGENTS.md` contains a `## Design Context` section from `impeccable init`, "
        "also generate 1-2 project-specific personas from the audience/brand info.",
        "If project instructions provide audience or brand context, also generate "
        "1-2 project-specific personas from that information.",
    )
    report = report.replace(
        "> *Consult the [Heuristics Scoring Guide](#heuristics-scoring-guide) section below.*",
        "> Consult `heuristics.md`.",
    )
    report = report.replace(
        "> *Consult the [Personas reference](#persona-based-design-testing) below.*",
        "> Consult `personas.md`.",
    )
    report = report.replace(
        "(see [Issue Severity below](#issue-severity-p0p3) for definitions)",
        "(see `heuristics.md` for severity definitions)",
    )
    review_method = (
        "# Impeccable Independent Review Method\n\n"
        "This filtered reference is review-only. The builder owns every code change; "
        "reviewers return evidence and findings but never edit the target.\n\n"
        f"{invariants}\n\n"
        f"{orchestration}\n\n"
        "The parent orchestrator decides whether delegation is available. When it is "
        "available, keep both review packets self-contained and prevent either reviewer "
        "from seeing the other's output before synthesis.\n\n"
        f"{assessment_a}\n\n"
        f"{assessment_b}\n\n"
        "For viewable targets, collect real desktop and mobile screenshots with the "
        "available browser tooling. Report missing browser access as an evidence gap; "
        "do not claim a visual check that did not run.\n\n"
        f"{report}"
    )
    review_method = review_method.replace(
        ".agents/skills/impeccable/scripts/detect.mjs",
        "<skill-root>/scripts/detect.mjs",
    )
    review_method = review_method.replace(
        "node <skill-root>/scripts/detect.mjs --json [target]",
        "node <skill-root>/scripts/detect.mjs --json --no-config [target]",
    )
    review_method = review_method.replace(
        "- Pass markup files/directories as `[target]`; do not pass CSS-only files.",
        "- This combined plugin always uses `--no-config`: it neither reads nor writes "
        "Impeccable configuration.\n"
        "- Pass markup files/directories as `[target]`; do not pass CSS-only files.",
    )
    review_method = filter_impeccable_lines(review_method)

    cognitive = between(
        critique, "### Cognitive Load Assessment", "### Heuristics Scoring Guide"
    )
    heuristics = between(
        critique, "### Heuristics Scoring Guide", "### Persona-Based Design Testing"
    )
    upstream_heuristic_severity = """| **P0** | Blocking | Prevents task completion entirely | Fix immediately; this is a showstopper |
| **P1** | Major | Causes significant difficulty or confusion | Fix before release |
| **P2** | Minor | Annoyance, but workaround exists | Fix in next pass |
| **P3** | Polish | Nice-to-fix, no real user impact | Fix if time permits |"""
    combined_heuristic_severity = """| **P0** | Blocking | Prevents task completion entirely | Blocks the gate |
| **P1** | Major | Causes significant difficulty or confusion | Blocks the gate when supported |
| **P2** | Minor | Material but non-blocking user impact | Advisory; parent may accept only when material and low-risk |
| **P3** | Polish | Nice-to-have, no real user impact | Advisory only; never auto-remediate |"""
    if upstream_heuristic_severity not in heuristics:
        raise SyncError(
            "Impeccable heuristic severity table changed upstream; review the "
            "unified P0-P3 transform before syncing"
        )
    heuristics = heuristics.replace(
        upstream_heuristic_severity, combined_heuristic_severity
    )
    personas = between(critique, "### Persona-Based Design Testing")
    personas = personas.replace(
        "If `AGENTS.md` contains a `## Design Context` section (generated by `impeccable init`), "
        "derive 1–2 additional personas from the audience and brand information:",
        "If project instructions provide audience or brand context, derive 1–2 additional "
        "personas from that information:",
    )
    technical = between(audit, "## Diagnostic Scan", "## Recommended Actions")
    upstream_severity = """Tag every issue with **P0-P3 severity**:
- **P0 Blocking**: Prevents task completion. Fix immediately
- **P1 Major**: Significant difficulty or WCAG AA violation. Fix before release
- **P2 Minor**: Annoyance, workaround exists. Fix in next pass
- **P3 Polish**: Nice-to-fix, no real user impact. Fix if time permits"""
    combined_severity = """Use the parent orchestration skill's unified P0-P3
contract. This reference does not assign severity automatically: a WCAG or
other standards violation supplies criterion and evidence, while demonstrated
user/task impact determines severity. P0/P1 block the gate; P2/P3 remain
advisory."""
    if upstream_severity not in technical:
        raise SyncError(
            "Impeccable audit severity block changed upstream; review the unified "
            "P0-P3 transform before syncing"
        )
    technical = technical.replace(upstream_severity, combined_severity)
    technical = (
        "# Impeccable Technical Audit\n\n"
        "Review-only: document measurable web implementation issues; do not fix them.\n\n"
        + technical
    )

    pieces = {
        "impeccable/review-method.md": (
            critique_path,
            critique_digest,
            "extract-review-method;drop-persistence-questions-actions-mutators;adapt-detector-path",
            review_method,
        ),
        "impeccable/cognitive-load.md": (
            critique_path,
            critique_digest,
            "extract-reference:cognitive-load",
            cognitive,
        ),
        "impeccable/heuristics.md": (
            critique_path,
            critique_digest,
            "extract-reference:heuristics-and-unified-severity",
            heuristics,
        ),
        "impeccable/personas.md": (
            critique_path,
            critique_digest,
            "extract-reference:personas",
            personas,
        ),
        "impeccable/technical-audit.md": (
            audit_path,
            audit_digest,
            "extract-diagnostic-and-report;normalize-severity-to-parent-contract;drop-actions-mutators",
            filter_impeccable_lines(technical),
        ),
    }
    if set(pieces) != set(config["included_references"]):
        raise SyncError("Impeccable 引用输出白名单与锁文件不一致")

    generated: dict[Path, bytes] = {}
    for relative, (source_path, digest, transform, content) in pieces.items():
        header = markdown_header(
            upstream="Impeccable",
            web_repository=config["web_repository"],
            commit=config["commit"],
            source_path=source_path,
            source_digest=digest,
            transform=transform,
            license_id=config["license"],
        )
        generated[REFERENCES_ROOT / relative] = (
            header + normalize_markdown(content)
        ).encode()
    return generated


def with_script_header(content: bytes, header: str) -> bytes:
    text = content.decode("utf-8")
    if text.startswith("#!"):
        first, separator, rest = text.partition("\n")
        return f"{first}\n{header}{rest}".encode()
    return (header + text).encode()


def generate_impeccable_detector(
    config: dict[str, Any],
    snapshot: GitSnapshot,
    source_hashes: dict[str, str],
) -> dict[Path, bytes]:
    generated: dict[Path, bytes] = {}
    sources: list[tuple[str, Path, str]] = [
        (
            config["detector_entrypoint"],
            SCRIPTS_ROOT / "detect.mjs",
            "copy",
        )
    ]
    prefix = config["detector_source_prefix"]
    sources.extend(
        (prefix + relative, SCRIPTS_ROOT / "detector" / relative, "copy")
        for relative in config["detector_files"]
    )

    for source_path, target_path, transform in sources:
        raw = snapshot.read(source_path)
        digest = sha256(raw)
        source_hashes[f"impeccable:{source_path}"] = digest
        content = raw
        if source_path.endswith("/detector/node/file-system.mjs"):
            extensions = b"""  '.jsx', '.tsx', '.js', '.ts',
  '.vue', '.svelte', '.astro',"""
            modern_extensions = b"""  '.jsx', '.tsx', '.js', '.ts',
  '.mjs', '.mts', '.cjs', '.cts',
  '.vue', '.svelte', '.astro',"""
            if content.count(extensions) != 1:
                raise SyncError("detector 可扫描扩展名结构变化")
            content = content.replace(extensions, modern_extensions)
            transform = "copy;add-modern-js-ts-module-extensions"
        elif source_path.endswith("/detector/cli/main.mjs"):
            old = b"""import {
  filterDetectionFindings,
  readDetectionConfig,
  shouldIgnoreDetectionFile,
} from '../../lib/impeccable-config.mjs';"""
            new = b"""// Combined-plugin policy: deterministic, read-only, and independent of
// .impeccable configuration. The orchestrator invokes the CLI with --no-config;
// these stubs also keep direct invocation from importing upstream mutators.
function readDetectionConfig() {
  return {
    ignoreRules: [],
    ignoreFiles: [],
    ignoreValues: [],
    designSystem: { enabled: false },
  };
}
function shouldIgnoreDetectionFile() {
  return false;
}
function filterDetectionFindings(findings) {
  return findings;
}"""
            if content.count(old) != 1:
                raise SyncError("detector CLI 配置依赖结构变化")
            content = content.replace(old, new)
            replacements = [
                (
                    b"Usage: impeccable detect [options] [file-or-dir-or-url...]",
                    b"Usage: impeccable detect [options] <file-or-dir...>",
                ),
                (
                    b"Scan files or URLs for UI anti-patterns and design quality issues.",
                    b"Scan local files for UI anti-patterns and design quality issues.",
                ),
                (
                    b"""  --viewport <WxH>    Browser viewport for URL scans (default 1280x800),
                      e.g. --viewport 390x844 for a mobile-width pass
""",
                    b"",
                ),
                (
                    b"""Project config:
  Respects .impeccable/config.json and .impeccable/config.local.json detector
  settings: detector.ignoreRules, detector.ignoreFiles, detector.ignoreValues,
  and detector.designSystem.enabled.
""",
                    b"""Combined-plugin policy:
  Project .impeccable configuration is not loaded. The orchestrator uses
  --no-config so every detector result is reviewed from raw evidence.
  An explicit local file or directory is required; stdin/hook and URL modes
  are not bundled.
""",
                ),
                (
                    b"""  URLs           Puppeteer full browser rendering (auto-detected;
                 http(s):// and file:// URLs)
""",
                    b"",
                ),
                (b"  impeccable detect https://example.com\n", b""),
            ]
            for before, after in replacements:
                if content.count(before) != 1:
                    raise SyncError(
                        "detector CLI 帮助结构变化，无法维持静态只读能力边界"
                    )
                content = content.replace(before, after)
            imports = b"""import {
  HTML_EXTENSIONS,
  buildImportGraph,"""
            imports_with_extensions = b"""import {
  HTML_EXTENSIONS,
  SCANNABLE_EXTENSIONS,
  buildImportGraph,"""
            if content.count(imports) != 1:
                raise SyncError("detector CLI 文件类型 import 结构变化")
            content = content.replace(imports, imports_with_extensions)
            target_setup = b"""  const targets = args.filter(a => !a.startsWith('--'));

  if (helpMode) { printUsage(); process.exit(0); }

  let allFindings = [];"""
            guarded_target_setup = b"""  const allowedFlags = new Set([
    '--json',
    '--quiet',
    '--no-config',
    '--no-inline-ignores',
    '--no-design-system',
    '--no-advisory',
    '--help',
    '--fast',
    '--gpt',
    '--gemini',
  ]);
  const unknownFlags = args.filter(
    arg => arg.startsWith('-') && !allowedFlags.has(arg)
  );
  if (unknownFlags.length > 0) {
    process.stderr.write(`Error: unknown option(s): ${unknownFlags.join(', ')}\\n`);
    process.exit(1);
  }
  const targets = args.filter(a => !a.startsWith('-'));

  if (helpMode) { printUsage(); process.exit(0); }
  if (targets.length === 0) {
    process.stderr.write(
      'Error: an explicit local file or directory target is required; ' +
      'stdin/hook input is not bundled.\\n'
    );
    process.exit(1);
  }

  let allFindings = [];"""
            if content.count(target_setup) != 1:
                raise SyncError("detector CLI 参数门禁结构变化")
            content = content.replace(target_setup, guarded_target_setup)
            browser_setup = b"""    const urlTargetCount = paths.filter(target => urlRe.test(target)).length;
    const browserDetector = urlTargetCount > 1 ? await createBrowserDetector() : null;"""
            browser_guard = b"""    const urlTargetCount = paths.filter(target => urlRe.test(target)).length;
    if (urlTargetCount > 0) {
      process.stderr.write(
        'Error: URL scanning is not bundled in Taste Impeccable. ' +
        'Use the runtime browser tools and screenshots for URL evidence.\\n'
      );
      process.exit(1);
    }
    const browserDetector = null;"""
            if content.count(browser_setup) != 1:
                raise SyncError("detector CLI URL 路由结构变化")
            content = content.replace(browser_setup, browser_guard)
            inaccessible_target = (
                b"catch { process.stderr.write(`Warning: cannot access ${target}\\n`); continue; }"
            )
            inaccessible_error = (
                b"catch { process.stderr.write(`Error: cannot access ${target}\\n`); "
                b"process.exit(1); }"
            )
            if content.count(inaccessible_target) != 1:
                raise SyncError("detector CLI 本地目标错误处理结构变化")
            content = content.replace(inaccessible_target, inaccessible_error)
            directory_scan = b"""          const files = walkDir(resolved)
            .filter(file => !shouldIgnoreDetectionFile(file, process.cwd(), detectionConfig));
          const htmlCount = files.filter(f => HTML_EXTENSIONS.has(path.extname(f).toLowerCase())).length;"""
            directory_guard = b"""          const files = walkDir(resolved)
            .filter(file => !shouldIgnoreDetectionFile(file, process.cwd(), detectionConfig));
          if (files.length === 0) {
            process.stderr.write(`Error: no scannable frontend files in ${target}\\n`);
            process.exit(1);
          }
          const htmlCount = files.filter(f => HTML_EXTENSIONS.has(path.extname(f).toLowerCase())).length;"""
            if content.count(directory_scan) != 1:
                raise SyncError("detector CLI 目录扫描结构变化")
            content = content.replace(directory_scan, directory_guard)
            file_scan = b"""        } else if (stat.isFile()) {
          if (shouldIgnoreDetectionFile(resolved, process.cwd(), detectionConfig)) continue;
          const ext = path.extname(resolved).toLowerCase();
          const fileOptions = scanOptionsFor(resolved);
          if (HTML_EXTENSIONS.has(ext)) {
            allFindings.push(...await detectHtml(resolved, fileOptions));
          } else {
            allFindings.push(...detectText(fs.readFileSync(resolved, 'utf-8'), resolved, fileOptions));
          }
        }"""
            guarded_file_scan = b"""        } else if (stat.isFile()) {
          if (shouldIgnoreDetectionFile(resolved, process.cwd(), detectionConfig)) continue;
          const ext = path.extname(resolved).toLowerCase();
          if (!SCANNABLE_EXTENSIONS.has(ext)) {
            process.stderr.write(`Error: unsupported frontend file type: ${target}\\n`);
            process.exit(1);
          }
          const fileOptions = scanOptionsFor(resolved);
          if (HTML_EXTENSIONS.has(ext)) {
            allFindings.push(...await detectHtml(resolved, fileOptions));
          } else {
            allFindings.push(...detectText(fs.readFileSync(resolved, 'utf-8'), resolved, fileOptions));
          }
        } else {
          process.stderr.write(`Error: unsupported target type: ${target}\\n`);
          process.exit(1);
        }"""
            if content.count(file_scan) != 1:
                raise SyncError("detector CLI 文件扫描结构变化")
            content = content.replace(file_scan, guarded_file_scan)
            transform = (
                "copy;replace-config-import-with-read-only-no-config-stubs;"
                "require-explicit-scannable-local-targets;reject-unknown-options;"
                "reject-url-inaccessible-empty-and-unsupported-targets"
            )
        header = script_header(
            upstream="Impeccable",
            web_repository=config["web_repository"],
            commit=config["commit"],
            source_path=source_path,
            source_digest=digest,
            transform=transform,
            license_id=config["license"],
        )
        generated[target_path] = with_script_header(content, header)
    return generated


def generate(
    lock: dict[str, Any],
) -> tuple[dict[Path, bytes], dict[str, str], dict[Path, bytes]]:
    upstreams = lock["upstreams"]
    snapshots: dict[str, GitSnapshot] = {}
    source_hashes: dict[str, str] = {}
    attribution_files: dict[Path, bytes] = {}
    try:
        for name in ("taste", "impeccable"):
            config = upstreams[name]
            snapshots[name] = GitSnapshot(config["repository"], config["commit"])
        taste = upstreams["taste"]
        impeccable = upstreams["impeccable"]
        generated = {}
        generated.update(generate_taste(taste, snapshots["taste"], source_hashes))
        generated.update(
            generate_impeccable_references(
                impeccable, snapshots["impeccable"], source_hashes
            )
        )
        generated.update(
            generate_impeccable_detector(
                impeccable, snapshots["impeccable"], source_hashes
            )
        )
        for name, config in upstreams.items():
            snapshot = snapshots[name]
            for key in ("license_path", "notice_path"):
                source_path = config.get(key)
                if source_path:
                    content = snapshot.read(source_path)
                    source_hashes[f"{name}:{source_path}"] = sha256(content)
                    target = ATTRIBUTION_TARGETS.get((name, key))
                    if target is None:
                        raise SyncError(f"缺少归属文件目标映射：{name}.{key}")
                    attribution_files[target] = content
        return (
            generated,
            dict(sorted(source_hashes.items())),
            attribution_files,
        )
    finally:
        for snapshot in snapshots.values():
            snapshot.close()


def artifact_records(generated: dict[Path, bytes]) -> dict[str, dict[str, str]]:
    records = {}
    for path, content in sorted(generated.items(), key=lambda item: str(item[0])):
        relative = path.relative_to(ROOT).as_posix()
        records[relative] = {"sha256": sha256(content)}
    return records


def write_generated(generated: dict[Path, bytes]) -> None:
    expected = set(generated)
    managed_roots = [
        REFERENCES_ROOT / "taste",
        REFERENCES_ROOT / "impeccable",
        SCRIPTS_ROOT / "detector",
    ]
    for managed_root in managed_roots:
        if not managed_root.exists():
            continue
        for path in managed_root.rglob("*"):
            if not path.is_file() or path in expected:
                continue
            try:
                prefix = path.read_bytes()[:4096].decode("utf-8", errors="ignore")
            except OSError:
                continue
            if GENERATED_MARKER in prefix:
                path.unlink()
    # detect.mjs 不在 detector 目录，也由本脚本明确管理。
    detect_path = SCRIPTS_ROOT / "detect.mjs"
    if detect_path.exists() and detect_path not in expected:
        prefix = detect_path.read_text(encoding="utf-8", errors="ignore")[:4096]
        if GENERATED_MARKER in prefix:
            detect_path.unlink()

    for path, content in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)


def notice_pin_block(lock: dict[str, Any]) -> str:
    labels = {"taste": "Taste", "impeccable": "Impeccable"}
    lines = [NOTICE_PIN_START]
    for name in ("taste", "impeccable"):
        config = lock["upstreams"][name]
        lines.append(
            f"- {labels[name]}：`{config['ref']}` → `{config['commit']}`"
        )
    lines.append(NOTICE_PIN_END)
    return "\n".join(lines)


def replace_notice_pin_block(text: str, lock: dict[str, Any]) -> str:
    start = text.find(NOTICE_PIN_START)
    end = text.find(NOTICE_PIN_END)
    if start < 0 or end < start:
        raise SyncError("THIRD_PARTY_NOTICES.md 缺少上游 pin 生成区块")
    end += len(NOTICE_PIN_END)
    return text[:start] + notice_pin_block(lock) + text[end:]


def write_attribution(
    lock: dict[str, Any], attribution_files: dict[Path, bytes]
) -> None:
    if set(attribution_files) != set(ATTRIBUTION_TARGETS.values()):
        raise SyncError("许可证/NOTICE 白名单不完整")
    for path, content in attribution_files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    notices_path = ROOT / "THIRD_PARTY_NOTICES.md"
    notices = notices_path.read_text(encoding="utf-8")
    notices_path.write_text(
        replace_notice_pin_block(notices, lock),
        encoding="utf-8",
    )


def check_attribution(
    lock: dict[str, Any], attribution_files: dict[Path, bytes]
) -> None:
    errors: list[str] = []
    for path, expected in attribution_files.items():
        if not path.is_file():
            errors.append(f"缺少归属文件：{path.relative_to(ROOT)}")
        elif path.read_bytes() != expected:
            errors.append(f"归属文件漂移：{path.relative_to(ROOT)}")
    notices_path = ROOT / "THIRD_PARTY_NOTICES.md"
    if not notices_path.is_file():
        errors.append("缺少 THIRD_PARTY_NOTICES.md")
    else:
        notices = notices_path.read_text(encoding="utf-8")
        if replace_notice_pin_block(notices, lock) != notices:
            errors.append("THIRD_PARTY_NOTICES.md 上游 pin 区块漂移")
    if errors:
        raise SyncError("\n".join(errors))


def check_generated(
    lock: dict[str, Any],
    generated: dict[Path, bytes],
    source_hashes: dict[str, str],
) -> None:
    errors: list[str] = []
    for path, expected in generated.items():
        if not path.exists():
            errors.append(f"缺少生成文件：{path.relative_to(ROOT)}")
            continue
        actual = path.read_bytes()
        if actual != expected:
            errors.append(f"生成文件漂移：{path.relative_to(ROOT)}")
    expected_records = artifact_records(generated)
    if lock.get("artifacts") != expected_records:
        errors.append("锁文件 artifacts 与固定提交生成结果不一致")
    if lock.get("source_hashes") != source_hashes:
        errors.append("锁文件 source_hashes 与固定提交不一致")
    if errors:
        raise SyncError("\n".join(errors) + "\n请审阅后运行 --update。")


def update_pins(lock: dict[str, Any]) -> list[str]:
    changes: list[str] = []
    for name, config in lock["upstreams"].items():
        resolved = resolve_ref(config["repository"], config["ref"])
        previous = config["commit"]
        if resolved != previous:
            changes.append(f"{name}: {previous} -> {resolved}")
            config["commit"] = resolved
    return changes


def command_update(lock: dict[str, Any]) -> None:
    previous_hashes = lock.get("source_hashes")
    previous_artifacts = lock.get("artifacts")
    review_state_missing = "pending_review" not in lock.get("policy", {})
    changes = update_pins(lock)
    generated, source_hashes, attribution_files = generate(lock)
    records = artifact_records(generated)
    write_generated(generated)
    write_attribution(lock, attribution_files)
    lock["source_hashes"] = source_hashes
    lock["artifacts"] = records
    content_changed = (
        review_state_missing
        or bool(changes)
        or previous_hashes != source_hashes
        or previous_artifacts != records
    )
    if content_changed:
        lock["policy"]["pending_review"] = True
        lock["reviewed_at"] = None
    save_lock(lock)
    if changes:
        print("已更新上游固定点：")
        for change in changes:
            print(f"- {change}")
        print("编排规则未改写；必须人工审阅生成差异。")
    print(
        f"已同步 {len(generated)} 个白名单产物及第三方归属文件；编排规则未改写。"
    )
    if content_changed:
        print(
            "锁文件已标记 pending_review=true；人工审阅 diff 后运行 --accept-review。"
        )


def command_check(lock: dict[str, Any]) -> None:
    generated, source_hashes, attribution_files = generate(lock)
    check_generated(lock, generated, source_hashes)
    check_attribution(lock, attribution_files)
    print(
        f"上游同步校验通过：{len(generated)} 个白名单产物、许可证和 NOTICE "
        "与锁文件一致。"
    )


def command_accept_review(lock: dict[str, Any]) -> None:
    generated, source_hashes, attribution_files = generate(lock)
    check_generated(lock, generated, source_hashes)
    check_attribution(lock, attribution_files)
    lock["policy"]["pending_review"] = False
    lock["reviewed_at"] = dt.date.today().isoformat()
    save_lock(lock)
    print(
        f"已记录人工审阅：reviewed_at={lock['reviewed_at']}，pending_review=false。"
    )


def command_check_updates(lock: dict[str, Any]) -> int:
    updates: list[str] = []
    for name, config in lock["upstreams"].items():
        if name == "impeccable" and config.get("release_tag_pattern"):
            latest_tag, latest_commit = resolve_latest_release(
                config["repository"], config["release_tag_pattern"]
            )
            current_tag = config["ref"].removeprefix("refs/tags/")
            if latest_tag != current_tag or latest_commit != config["commit"]:
                updates.append(
                    f"impeccable: {current_tag}@{config['commit']} -> "
                    f"{latest_tag}@{latest_commit}"
                )
        else:
            latest_commit = resolve_ref(config["repository"], config["ref"])
            if latest_commit != config["commit"]:
                updates.append(
                    f"{name}: {config['commit']} -> {latest_commit} ({config['ref']})"
                )
    if updates:
        print("发现上游更新：")
        for update in updates:
            print(f"- {update}")
        print("先人工更新 ref/审阅差异，再运行 --update；编排不会自动变化。")
        return 3
    print("未发现上游更新。")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="从锁定提交重建并只读比对")
    mode.add_argument(
        "--check-updates", action="store_true", help="只读检查跟踪分支/稳定 tag 更新"
    )
    mode.add_argument(
        "--update", action="store_true", help="解析配置 ref、同步白名单并更新哈希"
    )
    mode.add_argument(
        "--accept-review",
        action="store_true",
        help="在人工审阅 diff 后记录日期并解除 pending_review 门禁",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        lock = load_lock()
        if args.check:
            command_check(lock)
        elif args.check_updates:
            return command_check_updates(lock)
        elif args.accept_review:
            command_accept_review(lock)
        else:
            command_update(lock)
        return 0
    except (SyncError, OSError, UnicodeError) as exc:
        print(f"错误：{exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
