#!/usr/bin/env python3
"""离线校验插件结构、固定哈希、许可证与检测器烟测。"""

from __future__ import annotations

import datetime as dt
import hashlib
import importlib.util
import json
import re
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PLUGIN_ROOT = ROOT / "plugins" / "taste-impeccable"
SKILL_ROOT = PLUGIN_ROOT / "skills" / "design-frontend"
LOCK_PATH = ROOT / "upstreams.lock.json"
GENERATED_MARKER = "GENERATED by scripts/sync_upstreams.py"
SEMVER_RE = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)


class Validation:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.notes: list[str] = []

    def require(self, condition: bool, message: str) -> None:
        if not condition:
            self.errors.append(message)

    def run(self, label: str, command: list[str], *, cwd: Path = ROOT) -> None:
        result = subprocess.run(
            command,
            cwd=cwd,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        if result.returncode != 0:
            self.errors.append(f"{label} 失败：\n{result.stdout.rstrip()}")
        else:
            self.notes.append(f"{label}：通过")


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_json(path: Path, validation: Validation) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        validation.errors.append(f"无法读取 JSON {path.relative_to(ROOT)}：{exc}")
        return {}
    validation.require(isinstance(value, dict), f"{path.relative_to(ROOT)} 顶层必须是对象")
    return value if isinstance(value, dict) else {}


def load_yaml_dependency(validation: Validation) -> Any | None:
    if importlib.util.find_spec("yaml") is None:
        validation.errors.append(
            "缺少 PyYAML；先运行 python -m pip install -r requirements-dev.txt"
        )
        return None
    import yaml

    return yaml


def load_yaml_object(
    path: Path, validation: Validation, yaml_module: Any | None
) -> dict[str, Any]:
    if yaml_module is None:
        return {}
    try:
        value = yaml_module.safe_load(path.read_text(encoding="utf-8"))
    except OSError as exc:
        validation.errors.append(f"无法读取 YAML {path.relative_to(ROOT)}：{exc}")
        return {}
    except yaml_module.YAMLError as exc:
        validation.errors.append(f"YAML 无法解析 {path.relative_to(ROOT)}：{exc}")
        return {}
    validation.require(
        isinstance(value, dict), f"{path.relative_to(ROOT)} 顶层必须是对象"
    )
    return value if isinstance(value, dict) else {}


def validate_single_skill(
    validation: Validation, yaml_module: Any | None
) -> None:
    skill_files = sorted(PLUGIN_ROOT.glob("skills/**/SKILL.md"))
    validation.require(
        skill_files == [SKILL_ROOT / "SKILL.md"],
        "插件必须且只能暴露 skills/design-frontend/SKILL.md；实际为 "
        + ", ".join(str(path.relative_to(ROOT)) for path in skill_files),
    )
    skill = SKILL_ROOT / "SKILL.md"
    if skill.exists():
        text = skill.read_text(encoding="utf-8")
        validation.require(text.startswith("---\n"), "SKILL.md 缺少 YAML frontmatter")
        match = re.match(r"^---\n(.*?)\n---(?:\n|$)", text, re.DOTALL)
        validation.require(match is not None, "SKILL.md frontmatter 未闭合")
        if match is not None and yaml_module is not None:
            try:
                frontmatter = yaml_module.safe_load(match.group(1))
            except yaml_module.YAMLError as exc:
                validation.errors.append(f"SKILL.md frontmatter 无法解析：{exc}")
                return
            validation.require(
                isinstance(frontmatter, dict), "SKILL.md frontmatter 必须是对象"
            )
            if not isinstance(frontmatter, dict):
                return
            allowed = {"name", "description", "license", "allowed-tools", "metadata"}
            validation.require(
                not (set(frontmatter) - allowed),
                "SKILL.md frontmatter 含不支持字段："
                + ", ".join(sorted(set(frontmatter) - allowed)),
            )
            name = frontmatter.get("name")
            validation.require(name == "design-frontend", "SKILL.md name 必须是 design-frontend")
            validation.require(
                isinstance(name, str)
                and re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name) is not None
                and len(name) <= 64,
                "SKILL.md name 必须是最长 64 字符的合法 hyphen-case",
            )
            description = frontmatter.get("description")
            validation.require(
                isinstance(description, str)
                and bool(description.strip())
                and len(description) <= 1024
                and "<" not in description
                and ">" not in description,
                "SKILL.md description 必须是非空、最长 1024 字符且不含尖括号",
            )


def validate_skill_interface(
    validation: Validation, yaml_module: Any | None
) -> None:
    path = SKILL_ROOT / "agents" / "openai.yaml"
    payload = load_yaml_object(path, validation, yaml_module)
    if not payload:
        return
    allowed_top = {"interface", "policy", "dependencies"}
    validation.require(
        not (set(payload) - allowed_top),
        "agents/openai.yaml 含不支持字段："
        + ", ".join(sorted(set(payload) - allowed_top)),
    )
    interface = payload.get("interface")
    validation.require(isinstance(interface, dict), "agents/openai.yaml 缺少 interface")
    if not isinstance(interface, dict):
        return
    allowed_interface = {
        "display_name",
        "short_description",
        "icon_small",
        "icon_large",
        "brand_color",
        "default_prompt",
    }
    validation.require(
        not (set(interface) - allowed_interface),
        "agents/openai.yaml interface 含不支持字段："
        + ", ".join(sorted(set(interface) - allowed_interface)),
    )
    for field in ("display_name", "short_description", "default_prompt"):
        value = interface.get(field)
        validation.require(
            isinstance(value, str) and bool(value.strip()),
            f"agents/openai.yaml interface.{field} 必须是非空字符串",
        )
    default_prompt = interface.get("default_prompt")
    validation.require(
        isinstance(default_prompt, str)
        and "$taste-impeccable:design-frontend" in default_prompt,
        "agents/openai.yaml default_prompt 必须显式调用命名空间 Skill",
    )
    policy = payload.get("policy")
    if policy is not None:
        validation.require(isinstance(policy, dict), "agents/openai.yaml policy 必须是对象")
        if isinstance(policy, dict):
            validation.require(
                set(policy) <= {"allow_implicit_invocation"},
                "agents/openai.yaml policy 含不支持字段",
            )
            allow_implicit = policy.get("allow_implicit_invocation")
            validation.require(
                allow_implicit is None or isinstance(allow_implicit, bool),
                "policy.allow_implicit_invocation 必须是布尔值",
            )


def validate_review_agents(validation: Validation) -> None:
    agents_root = SKILL_ROOT / "agents"
    expected = {
        "impeccable_design_reviewer.toml",
        "impeccable_evidence_reviewer.toml",
    }
    actual = {path.name for path in agents_root.glob("impeccable_*.toml")}
    validation.require(actual == expected, "Impeccable reviewer 定义不完整或出现额外角色")
    for name in sorted(expected):
        path = agents_root / name
        if not path.is_file():
            continue
        try:
            config = tomllib.loads(path.read_text(encoding="utf-8"))
        except (OSError, tomllib.TOMLDecodeError) as exc:
            validation.errors.append(f"reviewer TOML 无法解析：{name}：{exc}")
            continue
        validation.require(
            config.get("sandbox_mode") == "read-only",
            f"{name} 必须声明 sandbox_mode=read-only",
        )
        for key in ("name", "description", "developer_instructions"):
            validation.require(bool(config.get(key)), f"{name} 缺少 {key}")
        instructions = config.get("developer_instructions", "")
        for marker in (
            "审校与修复是两个事务",
            "不实现修复",
            "不得把同一上下文续作 editor",
        ):
            validation.require(
                marker in instructions,
                f"{name} 缺少 reviewer 只读事务边界：{marker}",
            )


def validate_orchestration_contract(validation: Validation) -> None:
    skill_path = SKILL_ROOT / "SKILL.md"
    if not skill_path.is_file():
        return
    text = skill_path.read_text(encoding="utf-8")
    phases = [f"## Phase {index}:" for index in range(8)]
    positions = [text.find(phase) for phase in phases]
    validation.require(
        all(position >= 0 for position in positions),
        "SKILL.md 必须保留 Phase 0..7 完整编排",
    )
    if all(position >= 0 for position in positions):
        validation.require(
            positions == sorted(positions),
            "SKILL.md Phase 0..7 顺序被破坏",
        )
    required_contract = [
        "Taste owns direction and implementation",
        "Validation and remediation are separate transactions",
        "Do not run Taste and Impeccable as competing design skills",
        "The Taste/main maker applies accepted fixes",
        "Reviewer output is never an",
        "Reserved extension point — remediation executor (disabled)",
        "TASTE_OUT_OF_SCOPE",
        "freeze the review packet",
        "no conversation history",
        "codex exec --ephemeral --sandbox",
        "workspace fingerprint",
        "DEGRADED: single-context",
        "DEGRADED: no-browser",
        "--json --no-config",
        "at most two review cycles total",
        "no supported P0-P3 finding or unresolved detector advisory",
    ]
    for marker in required_contract:
        validation.require(
            marker in text,
            f"SKILL.md 编排契约缺失：{marker}",
        )

    impeccable_root = SKILL_ROOT / "references" / "impeccable"
    forbidden_reference_markers = [
        "$impeccable",
        "persisted snapshot",
        "Visual overlays",
        "[Human] tab",
        "generated by `impeccable init`",
        "WCAG AA violation. Fix before release",
        "Fix if time permits",
    ]
    for path in impeccable_root.glob("*.md"):
        reference = path.read_text(encoding="utf-8")
        found = [
            marker for marker in forbidden_reference_markers if marker in reference
        ]
        validation.require(
            not found,
            f"过滤后的 Impeccable 引用恢复了排除能力 {path.name}：{', '.join(found)}",
        )


def validate_manifest(validation: Validation) -> None:
    manifest_path = PLUGIN_ROOT / ".codex-plugin" / "plugin.json"
    manifest = load_json(manifest_path, validation)
    allowed = {
        "id",
        "name",
        "version",
        "description",
        "skills",
        "apps",
        "mcpServers",
        "interface",
        "author",
        "homepage",
        "repository",
        "license",
        "keywords",
    }
    validation.require(
        not (set(manifest) - allowed),
        "plugin manifest 含不支持字段："
        + ", ".join(sorted(set(manifest) - allowed)),
    )
    validation.require(manifest.get("name") == "taste-impeccable", "plugin name 不匹配")
    version = manifest.get("version")
    validation.require(
        isinstance(version, str) and SEMVER_RE.fullmatch(version) is not None,
        "plugin manifest version 必须是严格 semver",
    )
    validation.require(
        isinstance(manifest.get("description"), str)
        and bool(manifest["description"].strip()),
        "plugin manifest 缺少 description",
    )
    validation.require(
        manifest.get("skills") == "./skills/",
        "plugin manifest skills 必须指向 ./skills/",
    )
    validation.require(
        (PLUGIN_ROOT / "skills").is_dir(), "plugin manifest 指向的 skills 目录不存在"
    )
    author = manifest.get("author")
    validation.require(isinstance(author, dict), "plugin manifest author 必须是对象")
    if isinstance(author, dict):
        validation.require(
            set(author) <= {"name", "email", "url"},
            "plugin manifest author 含不支持字段",
        )
        validation.require(
            isinstance(author.get("name"), str) and bool(author["name"].strip()),
            "plugin manifest author.name 必须是非空字符串",
        )
    interface = manifest.get("interface")
    validation.require(isinstance(interface, dict), "plugin manifest interface 必须是对象")
    if isinstance(interface, dict):
        allowed_interface = {
            "displayName",
            "shortDescription",
            "longDescription",
            "developerName",
            "category",
            "capabilities",
            "websiteURL",
            "privacyPolicyURL",
            "termsOfServiceURL",
            "brandColor",
            "composerIcon",
            "logo",
            "logoDark",
            "screenshots",
            "defaultPrompt",
            "default_prompt",
        }
        validation.require(
            not (set(interface) - allowed_interface),
            "plugin manifest interface 含不支持字段："
            + ", ".join(sorted(set(interface) - allowed_interface)),
        )
        for field in (
            "displayName",
            "shortDescription",
            "longDescription",
            "developerName",
            "category",
        ):
            validation.require(
                isinstance(interface.get(field), str)
                and bool(interface[field].strip()),
                f"plugin manifest interface.{field} 必须是非空字符串",
            )
        capabilities = interface.get("capabilities")
        validation.require(
            isinstance(capabilities, list)
            and bool(capabilities)
            and all(isinstance(value, str) and value.strip() for value in capabilities),
            "plugin manifest interface.capabilities 必须是非空字符串数组",
        )
        default_prompt = interface.get(
            "defaultPrompt", interface.get("default_prompt")
        )
        validation.require(
            isinstance(default_prompt, (str, list))
            and (
                bool(default_prompt.strip())
                if isinstance(default_prompt, str)
                else bool(default_prompt)
                and all(
                    isinstance(value, str) and value.strip()
                    for value in default_prompt
                )
            ),
            "plugin manifest interface.defaultPrompt 必须是非空字符串或字符串数组",
        )
        brand_color = interface.get("brandColor")
        validation.require(
            brand_color is None
            or (
                isinstance(brand_color, str)
                and re.fullmatch(r"#[0-9A-Fa-f]{6}", brand_color) is not None
            ),
            "plugin manifest interface.brandColor 必须使用 #RRGGBB",
        )


def validate_marketplace(validation: Validation) -> None:
    path = ROOT / ".agents" / "plugins" / "marketplace.json"
    payload = load_json(path, validation)
    validation.require(
        payload.get("name") == "taste-impeccable",
        "marketplace name 必须是 taste-impeccable",
    )
    interface = payload.get("interface")
    validation.require(
        isinstance(interface, dict)
        and isinstance(interface.get("displayName"), str)
        and bool(interface["displayName"].strip()),
        "marketplace interface.displayName 必须是非空字符串",
    )
    plugins = payload.get("plugins")
    validation.require(
        isinstance(plugins, list) and len(plugins) == 1,
        "marketplace 必须且只能登记一个 plugin",
    )
    if not isinstance(plugins, list) or len(plugins) != 1:
        return
    entry = plugins[0]
    validation.require(isinstance(entry, dict), "marketplace plugin 条目必须是对象")
    if not isinstance(entry, dict):
        return
    validation.require(
        entry.get("name") == "taste-impeccable",
        "marketplace plugin name 不匹配",
    )
    source = entry.get("source")
    validation.require(
        source == {"source": "local", "path": "./plugins/taste-impeccable"},
        "marketplace source 必须精确指向本仓库 plugin",
    )
    policy = entry.get("policy")
    validation.require(
        policy == {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
        "marketplace policy 不完整",
    )
    validation.require(
        isinstance(entry.get("category"), str) and bool(entry["category"].strip()),
        "marketplace category 必须是非空字符串",
    )


def validate_lock_and_artifacts(
    validation: Validation, lock: dict[str, Any]
) -> None:
    validation.require(lock.get("schema_version") == 1, "锁文件 schema_version 必须为 1")
    validation.require(
        lock.get("transform_version") == 3,
        "锁文件 transform_version 必须为 3；转换器变更需显式升级",
    )
    validation.require(
        lock.get("role_contract_version") == 1,
        "锁文件 role_contract_version 必须为 1；角色或写权限变化需显式升级",
    )
    validation.require(
        lock.get("policy", {}).get("pending_review") is False,
        "上游同步仍处于 pending_review；人工审阅 diff 后运行 --accept-review",
    )
    reviewed_at = lock.get("reviewed_at")
    validation.require(
        isinstance(reviewed_at, str) and bool(reviewed_at),
        "锁文件缺少 reviewed_at",
    )
    if isinstance(reviewed_at, str):
        try:
            dt.date.fromisoformat(reviewed_at)
        except ValueError:
            validation.errors.append("锁文件 reviewed_at 必须是 ISO 日期")
    validation.require(
        lock.get("policy", {}).get("orchestration_is_manual") is True,
        "锁文件必须阻止上游自动改写编排",
    )
    policy = lock.get("policy", {})
    validation.require(
        policy.get("roles")
        == {
            "design_owner": "taste-main",
            "validation_owner": "impeccable-read-only",
            "remediation_owner": "taste-main",
        },
        "锁文件角色所有权必须保持 Taste/main 设计与修复、Impeccable 只读校验",
    )
    remediation_extension = (
        policy.get("extension_points", {}).get("bounded_remediation_executor", {})
    )
    validation.require(
        remediation_extension.get("enabled") is False,
        "受限 remediation executor 必须默认关闭",
    )
    validation.require(
        set(remediation_extension.get("activation_requires", []))
        == {
            "role_contract_version_bump",
            "semver_change",
            "updated_evals",
            "fresh_read_only_rereview",
        },
        "remediation executor 启用前置条件不完整",
    )
    upstreams = lock.get("upstreams", {})
    for name in ("taste", "impeccable"):
        config = upstreams.get(name, {})
        commit = config.get("commit", "")
        validation.require(
            isinstance(commit, str)
            and len(commit) == 40
            and all(char in "0123456789abcdef" for char in commit),
            f"{name} commit 不是 40 位小写 SHA",
        )
    impeccable = upstreams.get("impeccable", {})
    filtered_out = impeccable.get("filtered_out", {})
    validation.require(
        filtered_out.get("top_level_skill") == ".agents/skills/impeccable/SKILL.md",
        "Impeccable 顶层主设计 Skill 必须保持排除",
    )
    capabilities = set(filtered_out.get("capabilities", []))
    validation.require(
        {
            "hooks",
            "image generation",
            "mutation commands",
            "live editing",
        }
        <= capabilities,
        "Impeccable 关键冲突能力未完整记录在排除清单",
    )
    filtered_references = set(filtered_out.get("references", []))
    validation.require(
        {
            "polish.md",
            "layout.md",
            "typeset.md",
            "colorize.md",
            "bolder.md",
            "quieter.md",
        }
        <= filtered_references,
        "Impeccable reviewer mutator 排除清单不完整",
    )
    if impeccable.get("ref") == "refs/tags/skill-v4.0.1":
        validation.require(
            impeccable.get("commit")
            == "eda81f09378d32c93fec6d3cd8f1ecbf13595e15",
            "skill-v4.0.1 必须锁定 dereferenced commit，不能使用 annotated tag object",
        )

    artifacts = lock.get("artifacts", {})
    validation.require(bool(artifacts), "锁文件 artifacts 为空；请运行 sync --update")
    for relative, record in artifacts.items():
        path = ROOT / relative
        if not path.is_file():
            validation.errors.append(f"锁定产物缺失：{relative}")
            continue
        actual = digest(path)
        validation.require(
            actual == record.get("sha256"),
            f"产物哈希漂移：{relative}，期望 {record.get('sha256')}，实际 {actual}",
        )
        prefix = path.read_bytes()[:4096].decode("utf-8", errors="ignore")
        validation.require(
            GENERATED_MARKER in prefix,
            f"锁定产物缺少 generated/source header：{relative}",
        )

    source_hashes = lock.get("source_hashes", {})
    license_targets = {
        "taste:LICENSE": ROOT / "LICENSES" / "TASTE-MIT.txt",
        "impeccable:LICENSE": ROOT / "LICENSES" / "IMPECCABLE-APACHE-2.0.txt",
        "impeccable:NOTICE.md": ROOT / "LICENSES" / "IMPECCABLE-NOTICE.md",
    }
    for source_key, target in license_targets.items():
        if not target.is_file():
            validation.errors.append(f"第三方许可证文件缺失：{target.relative_to(ROOT)}")
            continue
        validation.require(
            digest(target) == source_hashes.get(source_key),
            f"第三方许可证不是锁定上游原文：{target.relative_to(ROOT)}",
        )
    notices = ROOT / "THIRD_PARTY_NOTICES.md"
    if not notices.is_file():
        validation.errors.append("缺少 THIRD_PARTY_NOTICES.md")
    else:
        text = notices.read_text(encoding="utf-8")
        for config in upstreams.values():
            validation.require(
                config.get("commit", "") in text,
                f"THIRD_PARTY_NOTICES.md 未记录 {config.get('commit')}",
            )


def validate_generated_allowlist(validation: Validation, lock: dict[str, Any]) -> None:
    allowed = set(lock.get("artifacts", {}))
    managed = [
        SKILL_ROOT / "references" / "taste",
        SKILL_ROOT / "references" / "impeccable",
        SKILL_ROOT / "scripts" / "detector",
    ]
    detected: set[str] = set()
    for root in managed:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_file():
                detected.add(path.relative_to(ROOT).as_posix())
    detect_entry = SKILL_ROOT / "scripts" / "detect.mjs"
    if detect_entry.is_file():
        detected.add(detect_entry.relative_to(ROOT).as_posix())
    validation.require(
        detected == allowed,
        "生成白名单与磁盘不一致；额外="
        + repr(sorted(detected - allowed))
        + " 缺少="
        + repr(sorted(allowed - detected)),
    )
    forbidden_write_tokens = {
        "writeFileSync",
        "writeDetectionConfig",
        "ensureConfigGitExclude",
        "mkdirSync",
        "unlinkSync",
        "rmSync",
        "appendFileSync",
        "createWriteStream",
    }
    detector_root = SKILL_ROOT / "scripts" / "detector"
    for path in detector_root.rglob("*"):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        found = sorted(token for token in forbidden_write_tokens if token in text)
        validation.require(
            not found,
            f"只读 detector 含写入能力 {path.relative_to(ROOT)}：{', '.join(found)}",
        )


def validate_detector(validation: Validation) -> None:
    node = shutil_which("node")
    if not node:
        validation.errors.append("未找到 node，无法验证 Impeccable detector")
        return
    entry = SKILL_ROOT / "scripts" / "detect.mjs"
    fixture = ROOT / "tests" / "fixtures" / "ai-slop.html"
    result = subprocess.run(
        [node, str(entry), "--json", "--no-config", str(fixture)],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    validation.require(
        result.returncode == 2,
        f"detector fixture 应以 findings 状态 2 退出，实际 {result.returncode}：{result.stderr}",
    )
    try:
        findings = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        validation.errors.append(f"detector 未输出 JSON：{exc}\n{result.stdout[:1000]}")
        return
    validation.require(isinstance(findings, list) and bool(findings), "detector fixture 未命中")
    ids = {
        item.get("antipattern")
        for item in findings
        if isinstance(item, dict) and not item.get("advisory")
    }
    expected = {
        "marketing-buzzword",
        "overused-font",
        "side-tab",
        "single-font",
    }
    validation.require(
        expected <= ids,
        "detector fixture 丢失稳定规则；"
        f"缺少 {sorted(expected - ids)}，实际 {sorted(value for value in ids if value)}",
    )
    validation.notes.append(f"detector fixture：命中 {len(findings)} 条")

    url_result = subprocess.run(
        [node, str(entry), "--json", "--no-config", fixture.resolve().as_uri()],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    validation.require(
        url_result.returncode == 1,
        f"detector URL 输入必须显式拒绝，不能假绿；实际退出 {url_result.returncode}",
    )
    validation.require(
        "URL scanning is not bundled" in url_result.stderr,
        f"detector URL 拒绝缺少可行动说明：{url_result.stderr}",
    )
    validation.require(
        url_result.stdout.strip() != "[]",
        "detector URL 依赖缺失时不得输出空 findings 冒充 clean",
    )
    validation.notes.append("detector URL 输入：显式拒绝，无假绿")

    missing_target = ROOT / "tests" / "fixtures" / "does-not-exist.html"
    missing_result = subprocess.run(
        [node, str(entry), "--json", "--no-config", str(missing_target)],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    validation.require(
        missing_result.returncode == 1,
        "detector 不可访问目标必须失败，不能以空 findings 假绿",
    )
    validation.require(
        "Error: cannot access" in missing_result.stderr,
        f"detector 不可访问目标缺少可行动说明：{missing_result.stderr}",
    )
    validation.require(
        missing_result.stdout.strip() != "[]",
        "detector 不可访问目标不得输出空 findings 冒充 clean",
    )
    validation.notes.append("detector 不可访问目标：显式失败，无假绿")

    with tempfile.TemporaryDirectory(prefix="taste-impeccable-empty-") as empty:
        empty_result = subprocess.run(
            [node, str(entry), "--json", "--no-config", empty],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
    validation.require(
        empty_result.returncode == 1,
        "detector 空目录必须失败，不能以空 findings 假绿",
    )
    validation.require(
        "no scannable frontend files" in empty_result.stderr,
        f"detector 空目录缺少可行动说明：{empty_result.stderr}",
    )
    validation.require(
        empty_result.stdout.strip() != "[]",
        "detector 空目录不得输出空 findings 冒充 clean",
    )
    validation.notes.append("detector 空目录：显式失败，无假绿")

    no_target = subprocess.run(
        [node, str(entry), "--json", "--no-config"],
        cwd=ROOT,
        input="",
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    validation.require(
        no_target.returncode == 1
        and "explicit local file or directory target is required" in no_target.stderr
        and no_target.stdout.strip() != "[]",
        "detector 空 stdin/无目标必须显式失败",
    )

    hook_input = subprocess.run(
        [node, str(entry), "--json", "--no-config"],
        cwd=ROOT,
        input='{"tool_input":{"file_path":"/definitely/missing.html"}}',
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    validation.require(
        hook_input.returncode == 1
        and "stdin/hook input is not bundled" in hook_input.stderr
        and hook_input.stdout.strip() != "[]",
        "detector hook stdin 必须显式拒绝，不能把 JSON 当源码假绿",
    )

    unsupported_file = subprocess.run(
        [node, str(entry), "--json", "--no-config", str(ROOT / "README.md")],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    validation.require(
        unsupported_file.returncode == 1
        and "unsupported frontend file type" in unsupported_file.stderr
        and unsupported_file.stdout.strip() != "[]",
        "detector 不支持的普通文件必须显式失败",
    )

    unsupported_target = subprocess.run(
        [node, str(entry), "--json", "--no-config", "/dev/null"],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    validation.require(
        unsupported_target.returncode == 1
        and "unsupported target type" in unsupported_target.stderr
        and unsupported_target.stdout.strip() != "[]",
        "detector 非普通文件目标必须显式失败",
    )

    mixed_targets = subprocess.run(
        [
            node,
            str(entry),
            "--json",
            "--no-config",
            str(ROOT / "README.md"),
            str(entry),
        ],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    validation.require(
        mixed_targets.returncode == 1
        and "unsupported frontend file type" in mixed_targets.stderr
        and mixed_targets.stdout.strip() != "[]",
        "detector 多目标不得用合法目标掩盖未扫描目标",
    )

    unknown_option = subprocess.run(
        [node, str(entry), "--json", "--no-config", "--bogus", str(fixture)],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    validation.require(
        unknown_option.returncode == 1
        and "unknown option" in unknown_option.stderr
        and unknown_option.stdout.strip() != "[]",
        "detector 未知参数必须 usage failure，不能静默错扫",
    )
    with tempfile.TemporaryDirectory(prefix="taste-impeccable-modules-") as modules:
        module_dir = Path(modules)
        module_file = module_dir / "ui.mjs"
        module_file.write_text(fixture.read_text(encoding="utf-8"), encoding="utf-8")
        module_file_result = subprocess.run(
            [node, str(entry), "--json", "--no-config", str(module_file)],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        module_dir_result = subprocess.run(
            [node, str(entry), "--json", "--no-config", str(module_dir)],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
    for label, module_result in (
        ("ESM 文件", module_file_result),
        ("仅含 ESM 的目录", module_dir_result),
    ):
        validation.require(
            module_result.returncode in {0, 2},
            f"detector {label}必须可扫描，实际退出 {module_result.returncode}："
            f"{module_result.stderr}",
        )
        try:
            module_payload = json.loads(module_result.stdout)
        except json.JSONDecodeError:
            module_payload = None
        validation.require(
            isinstance(module_payload, list),
            f"detector {label}必须输出 JSON findings 数组",
        )
    validation.notes.append("detector 输入门禁：stdin/hook/类型/多目标/未知参数均无假绿")
    validation.notes.append("detector 现代 JS/TS 模块扩展：文件与目录均可扫描")


def validate_evals(validation: Validation) -> None:
    cases_path = ROOT / "evals" / "cases.json"
    schema_path = ROOT / "evals" / "plan-trace.schema.json"
    if not cases_path.is_file():
        validation.errors.append("缺少升级回归接口 evals/cases.json")
        return
    payload = load_json(cases_path, validation)
    schema = load_json(schema_path, validation)
    event_values = (
        schema.get("properties", {})
        .get("events", {})
        .get("items", {})
        .get("enum")
    )
    validation.require(
        isinstance(event_values, list)
        and bool(event_values)
        and len(event_values) == len(set(event_values)),
        "plan-trace schema events enum 必须是非空且无重复的数组",
    )
    event_set = set(event_values) if isinstance(event_values, list) else set()
    validation.require(payload.get("schema_version") == 2, "evals schema_version 必须为 2")
    cases = payload.get("cases")
    validation.require(isinstance(cases, list) and bool(cases), "evals cases 必须是非空数组")
    if not isinstance(cases, list):
        return
    seen: set[str] = set()
    required = {
        "prompt",
        "should_invoke",
        "expected_scope",
        "expected_review_mode",
        "required_events",
        "before_edges",
        "forbidden_events",
    }
    for index, case in enumerate(cases):
        if not isinstance(case, dict):
            validation.errors.append(f"evals cases[{index}] 必须是对象")
            continue
        case_id = case.get("id")
        validation.require(
            isinstance(case_id, str) and bool(case_id.strip()),
            f"evals cases[{index}] 缺少非空 id",
        )
        if isinstance(case_id, str):
            validation.require(case_id not in seen, f"eval case id 重复：{case_id}")
            seen.add(case_id)
        missing = sorted(required - set(case))
        validation.require(
            not missing,
            f"eval case {case_id or index} 缺少字段：{', '.join(missing)}",
        )
        if missing:
            continue
        validation.require(
            isinstance(case["should_invoke"], bool),
            f"eval case {case_id or index} should_invoke 必须是布尔值",
        )
        validation.require(
            case["expected_scope"]
            in {"IN_SCOPE", "CONDITIONAL", "TASTE_OUT_OF_SCOPE", "NOT_APPLICABLE"},
            f"eval case {case_id or index} expected_scope 非法",
        )
        validation.require(
            case["expected_review_mode"]
            in {"sandboxed_independent", "single_context_degraded", "not_applicable"},
            f"eval case {case_id or index} expected_review_mode 非法",
        )
        valid_event_fields = True
        for field in ("required_events", "forbidden_events"):
            trace = case[field]
            field_valid = (
                isinstance(trace, list)
                and all(isinstance(event, str) for event in trace)
                and len(trace) == len(set(trace))
            )
            validation.require(
                field_valid,
                f"eval case {case_id or index} {field} 必须是无重复字符串数组",
            )
            if field_valid:
                validation.require(
                    set(trace) <= event_set,
                    f"eval case {case_id or index} {field} 含 schema 外事件："
                    + ", ".join(sorted(set(trace) - event_set)),
                )
            else:
                valid_event_fields = False
        required_events = case["required_events"]
        forbidden_events = case["forbidden_events"]
        if valid_event_fields:
            validation.require(
                not (set(required_events) & set(forbidden_events)),
                f"eval case {case_id or index} 必需与禁止事件重叠",
            )
        edges = case["before_edges"]
        valid_edges = (
            isinstance(edges, list)
            and all(
                isinstance(edge, list)
                and len(edge) == 2
                and all(isinstance(event, str) for event in edge)
                for edge in edges
            )
        )
        validation.require(
            valid_edges,
            f"eval case {case_id or index} before_edges 必须是二元字符串数组",
        )
        if valid_edges and valid_event_fields:
            edge_pairs = [tuple(edge) for edge in edges]
            validation.require(
                len(edge_pairs) == len(set(edge_pairs)),
                f"eval case {case_id or index} before_edges 含重复边",
            )
            endpoints = {event for edge in edges for event in edge}
            validation.require(
                endpoints <= set(required_events),
                f"eval case {case_id or index} before_edges 端点必须属于 required_events",
            )
            validation.require(
                all(before != after for before, after in edges),
                f"eval case {case_id or index} before_edges 不得自环",
            )
            adjacency = {event: set() for event in required_events}
            indegree = {event: 0 for event in required_events}
            for before, after in edges:
                if before not in adjacency or after not in indegree:
                    continue
                if after not in adjacency[before]:
                    adjacency[before].add(after)
                    indegree[after] += 1
            ready = [event for event, degree in indegree.items() if degree == 0]
            visited = 0
            while ready:
                event = ready.pop()
                visited += 1
                for successor in adjacency[event]:
                    indegree[successor] -= 1
                    if indegree[successor] == 0:
                        ready.append(successor)
            validation.require(
                visited == len(required_events),
                f"eval case {case_id or index} before_edges 含环",
            )
        if case["should_invoke"]:
            validation.require(
                valid_event_fields
                and "design_frontend_skill_invoked" in required_events,
                f"eval case {case_id or index} 必须要求 Skill 调用事件",
            )
        else:
            validation.require(
                valid_event_fields
                and "design_frontend_skill_invoked" in forbidden_events,
                f"eval case {case_id or index} 必须禁止 Skill 调用事件",
            )

    baseline_check = ROOT / "scripts" / "run_plan_evals.py"
    if baseline_check.is_file():
        validation.run(
            "GPT-5.6 Sol plan-trace baseline",
            [sys.executable, str(baseline_check), "--check"],
        )
    else:
        validation.errors.append("缺少 scripts/run_plan_evals.py")


def shutil_which(command: str) -> str | None:
    # 避免为了一个查询引入额外运行时依赖。
    import shutil

    return shutil.which(command)


def run_optional_official_validators(validation: Validation) -> None:
    codex_skills = Path.home() / ".codex" / "skills" / ".system"
    candidates = [
        (
            "Skill 官方校验",
            codex_skills / "skill-creator" / "scripts" / "quick_validate.py",
            SKILL_ROOT,
        ),
        (
            "Plugin 官方校验",
            codex_skills / "plugin-creator" / "scripts" / "validate_plugin.py",
            PLUGIN_ROOT,
        ),
    ]
    yaml_available = importlib.util.find_spec("yaml") is not None
    for label, script, target in candidates:
        if script.is_file() and yaml_available:
            validation.run(label, [sys.executable, str(script), str(target)])
        else:
            reason = "脚本缺失" if not script.is_file() else "当前 Python 缺少 PyYAML"
            validation.notes.append(
                f"{label}：不可调用（{reason}），已执行内建结构校验"
            )


def main() -> int:
    validation = Validation()
    yaml_module = load_yaml_dependency(validation)
    lock = load_json(LOCK_PATH, validation)
    validate_single_skill(validation, yaml_module)
    validate_skill_interface(validation, yaml_module)
    validate_review_agents(validation)
    validate_orchestration_contract(validation)
    validate_manifest(validation)
    validate_marketplace(validation)
    validate_lock_and_artifacts(validation, lock)
    validate_generated_allowlist(validation, lock)
    validate_detector(validation)
    validate_evals(validation)
    run_optional_official_validators(validation)
    for note in validation.notes:
        print(f"✓ {note}")
    if validation.errors:
        for error in validation.errors:
            print(f"✗ {error}", file=sys.stderr)
        return 1
    print("插件校验通过。")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
