// GENERATED by scripts/sync_upstreams.py; DO NOT EDIT.
// upstream: Impeccable
// source: https://github.com/pbakaus/impeccable/blob/eda81f09378d32c93fec6d3cd8f1ecbf13595e15/.agents/skills/impeccable/scripts/detector/findings.mjs
// commit: eda81f09378d32c93fec6d3cd8f1ecbf13595e15
// source_sha256: 8b8af7212c8515d6791a8af1375d0619a9f9a707a881e6fbd850e4216b3f8eca
// transform: copy
// SPDX-License-Identifier: Apache-2.0

import { getAntipattern } from './registry/antipatterns.mjs';

function getAP(id) {
  return getAntipattern(id);
}

function finding(id, filePath, snippet, line = 0) {
  const ap = getAP(id);
  const base = { antipattern: id, name: ap.name, description: ap.description, severity: ap.severity || 'warning', category: ap.category || null, file: filePath, line, snippet };
  // Advisory findings are detected but reported separately and never counted as
  // failures. Carry the flag on the finding so every consumer (CLI, JSON, hook)
  // can partition without a registry lookup. Only stamped when true to keep the
  // finding shape stable for the vast majority of rules.
  if (ap.advisory === true) base.advisory = true;
  return base;
}

export { getAP, finding };
