#!/usr/bin/env node
// GENERATED by scripts/sync_upstreams.py; DO NOT EDIT.
// upstream: Impeccable
// source: https://github.com/pbakaus/impeccable/blob/eda81f09378d32c93fec6d3cd8f1ecbf13595e15/.agents/skills/impeccable/scripts/detect.mjs
// commit: eda81f09378d32c93fec6d3cd8f1ecbf13595e15
// source_sha256: f5dfd05ca1e314acd8ed79c6301a20a1b844f2eb6691bd63e04116a8e7efb187
// transform: copy
// SPDX-License-Identifier: Apache-2.0


import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const candidates = [
  path.join(__dirname, 'detector', 'detect-antipatterns.mjs'),
  path.join(__dirname, '..', '..', 'cli', 'engine', 'detect-antipatterns.mjs'),
];
const detectorPath = candidates.find(p => fs.existsSync(p));

if (!detectorPath) {
  process.stderr.write('Error: bundled detector not found.\n');
  process.exit(1);
}

const { detectCli } = await import(pathToFileURL(detectorPath));

await detectCli();
